"""meal model added

Revision ID: 47cf2b093e5d
Revises: 5eeccf0557bb
Create Date: 2021-04-26 17:22:27.251773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47cf2b093e5d'
down_revision = '5eeccf0557bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_date', sa.Date(), nullable=False),
    sa.Column('carbohydrate_portions', sa.Integer(), nullable=True),
    sa.Column('fruit_portions', sa.Integer(), nullable=True),
    sa.Column('vegetable_portions', sa.Integer(), nullable=True),
    sa.Column('dairy_portions', sa.Integer(), nullable=True),
    sa.Column('protein_portions', sa.Integer(), nullable=True),
    sa.Column('polyunsaturated_fats_portions', sa.Integer(), nullable=True),
    sa.Column('monounsaturated_fats_portions', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Meal_user_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Meal'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Meal')
    # ### end Alembic commands ###
