"""diet model added

Revision ID: 5eeccf0557bb
Revises: d7d8fa2c4ebc
Create Date: 2021-04-26 13:25:13.013979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eeccf0557bb'
down_revision = 'd7d8fa2c4ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Diet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carbohydrate_portions', sa.Integer(), nullable=False),
    sa.Column('fruit_portions', sa.Integer(), nullable=False),
    sa.Column('vegetable_portions', sa.Integer(), nullable=False),
    sa.Column('dairy_portions', sa.Integer(), nullable=False),
    sa.Column('protein_portions', sa.Integer(), nullable=False),
    sa.Column('polyunsaturated_fats_portions', sa.Integer(), nullable=False),
    sa.Column('monounsaturated_fats_portions', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name=op.f('fk_Diet_user_id_User')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_Diet'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Diet')
    # ### end Alembic commands ###
